# Generated by Django 2.2.10 on 2020-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200708_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ClUi', 'Clothes and Uniforms'), ('PhAc', 'Phones & Accessories'), ('JeWa', 'Jewelry & Watches'), ('BaSh', 'Bags & Shoes'), ('HA', 'Home Appliance'), ('BeHeHa', 'Beauty & Health, Hair'), ('Ap', 'Apartments'), ('Ho', 'Houses')], max_length=50),
        ),
    ]
