# Generated by Django 3.0.5 on 2020-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
