# Generated by Django 3.0.5 on 2020-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Full_name',
            field=models.CharField(help_text='Ex: John doe', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='it will be your Username on site', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
